---
apiVersion: k3d.io/v1alpha2
kind: Simple
image: rancher/k3s:v1.20.4-k3s1 
ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 8443:443 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
